// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloneProfile(arg1) {
  return window['go']['main']['App']['CloneProfile'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateProfile(arg1, arg2) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteUserMacro(arg1) {
  return window['go']['main']['App']['DeleteUserMacro'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function ExportCDRCSV(arg1, arg2) {
  return window['go']['main']['App']['ExportCDRCSV'](arg1, arg2);
}

export function FlushRegistration(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FlushRegistration'](arg1, arg2, arg3, arg4);
}

export function GetCDRRaw(arg1) {
  return window['go']['main']['App']['GetCDRRaw'](arg1);
}

export function GetChannelVars(arg1, arg2) {
  return window['go']['main']['App']['GetChannelVars'](arg1, arg2);
}

export function GetDashboardStats(arg1) {
  return window['go']['main']['App']['GetDashboardStats'](arg1);
}

export function GetGlobalVars(arg1) {
  return window['go']['main']['App']['GetGlobalVars'](arg1);
}

export function HangupCall(arg1, arg2, arg3) {
  return window['go']['main']['App']['HangupCall'](arg1, arg2, arg3);
}

export function ListChannels(arg1) {
  return window['go']['main']['App']['ListChannels'](arg1);
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function ListModules(arg1) {
  return window['go']['main']['App']['ListModules'](arg1);
}

export function ListPluginStates(arg1) {
  return window['go']['main']['App']['ListPluginStates'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListRegistrations(arg1) {
  return window['go']['main']['App']['ListRegistrations'](arg1);
}

export function ListSofiaProfiles(arg1) {
  return window['go']['main']['App']['ListSofiaProfiles'](arg1);
}

export function ListUserMacros() {
  return window['go']['main']['App']['ListUserMacros']();
}

export function PluginCall(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PluginCall'](arg1, arg2, arg3, arg4);
}

export function QueryCDR(arg1, arg2) {
  return window['go']['main']['App']['QueryCDR'](arg1, arg2);
}

export function RecordCall(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecordCall'](arg1, arg2, arg3);
}

export function SaveUserMacro(arg1) {
  return window['go']['main']['App']['SaveUserMacro'](arg1);
}

export function SendAPI(arg1, arg2) {
  return window['go']['main']['App']['SendAPI'](arg1, arg2);
}

export function SendBgAPI(arg1, arg2) {
  return window['go']['main']['App']['SendBgAPI'](arg1, arg2);
}

export function SessionStates() {
  return window['go']['main']['App']['SessionStates']();
}

export function SetChannelVar(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetChannelVar'](arg1, arg2, arg3, arg4);
}

export function SetEventMonitor(arg1, arg2) {
  return window['go']['main']['App']['SetEventMonitor'](arg1, arg2);
}

export function SetGlobalVar(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetGlobalVar'](arg1, arg2, arg3);
}

export function SetPluginEnabled(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPluginEnabled'](arg1, arg2, arg3);
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}

export function TransferCall(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['TransferCall'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2);
}
