// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';
import {session} from '../models';

export function CloneProfile(arg1:string):Promise<store.Profile>;

export function Connect(arg1:string):Promise<void>;

export function CreateProfile(arg1:store.Profile,arg2:main.ProfileSecrets):Promise<store.Profile>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteUserMacro(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function ExportCDRCSV(arg1:string,arg2:store.CDRFilter):Promise<string>;

export function FlushRegistration(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetCDRRaw(arg1:number):Promise<string>;

export function GetChannelVars(arg1:string,arg2:string):Promise<main.ChannelDump>;

export function GetDashboardStats(arg1:string):Promise<main.DashboardStats>;

export function GetGlobalVars(arg1:string):Promise<Array<main.KV>>;

export function HangupCall(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListChannels(arg1:string):Promise<Array<Record<string, string>>>;

export function ListDirectory(arg1:string):Promise<Array<main.DirectoryUser>>;

export function ListModules(arg1:string):Promise<Array<main.FSModule>>;

export function ListPluginStates(arg1:string):Promise<Array<main.PluginState>>;

export function ListProfiles():Promise<Array<store.Profile>>;

export function ListRegistrations(arg1:string):Promise<Array<main.Registration>>;

export function ListSofiaProfiles(arg1:string):Promise<Array<string>>;

export function ListUserMacros():Promise<Array<store.Macro>>;

export function PluginCall(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<any>;

export function QueryCDR(arg1:string,arg2:store.CDRFilter):Promise<store.CDRPage>;

export function RecordCall(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function SaveUserMacro(arg1:store.Macro):Promise<store.Macro>;

export function SendAPI(arg1:string,arg2:string):Promise<string>;

export function SendBgAPI(arg1:string,arg2:string):Promise<string>;

export function SessionStates():Promise<Record<string, session.State>>;

export function SetChannelVar(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetEventMonitor(arg1:string,arg2:boolean):Promise<void>;

export function SetGlobalVar(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetPluginEnabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function TestConnection(arg1:store.Profile,arg2:main.ProfileSecrets):Promise<main.TestResult>;

export function TransferCall(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function UpdateProfile(arg1:store.Profile,arg2:main.ProfileSecrets):Promise<void>;
